# Generated by Django 6.0.3 on 2026-03-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_created', 'Task Created'), ('task_assigned', 'Task Assigned'), ('task_status_changed', 'Task Status Changed'), ('added_to_workspace', 'Added To Workspace'), ('role_updated', 'Role Updated')], max_length=50),
        ),
    ]
